// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyGiaoVienCSDLNC.Data;

#nullable disable

namespace QuanLyGiaoVienCSDLNC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250602165009_NoiDungGiangDay")]
    partial class NoiDungGiangDay
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.DTOs.NCKH.TaiNCKHListItemDto", b =>
                {
                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaTaiNCKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("QuyRaGioChuan")
                        .HasColumnType("real");

                    b.Property<int>("SoTacGia")
                        .HasColumnType("int");

                    b.Property<string>("TenCongTrinhKhoaHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoaiNCKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.BoMon", b =>
                {
                    b.Property<string>("MaBM")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaChuNhiemBM")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenBM")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaBM");

                    b.HasIndex("MaKhoa");

                    b.ToTable("BoMon", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.ChiTietCongTacKhac", b =>
                {
                    b.Property<string>("MaChiTietCongTacKhac")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaCongTacKhac")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaGV")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaChiTietCongTacKhac");

                    b.HasIndex("MaCongTacKhac");

                    b.HasIndex("MaGV");

                    b.ToTable("ChiTietCongTacKhac", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.ChiTietGiangDay", b =>
                {
                    b.Property<string>("MaChiTietGiangDay")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MaGV")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaTaiGiangDay")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("NoiDungGiangDay")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SoTiet")
                        .HasColumnType("int");

                    b.Property<double>("SoTietQuyDoi")
                        .HasColumnType("float");

                    b.HasKey("MaChiTietGiangDay");

                    b.HasIndex("MaGV");

                    b.HasIndex("MaTaiGiangDay");

                    b.ToTable("ChiTietGiangDay", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.ChiTietNCKH", b =>
                {
                    b.Property<string>("MaChiTietNCKH")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaGV")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaTaiNCKH")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<double>("SoGio")
                        .HasColumnType("float");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaChiTietNCKH");

                    b.HasIndex("MaGV");

                    b.HasIndex("MaTaiNCKH");

                    b.ToTable("ChiTietNCKH", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.ChiTietTaiKhaoThi", b =>
                {
                    b.Property<string>("MaChiTietTaiKhaoThi")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaGV")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaTaiKhaoThi")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("SoBai")
                        .HasColumnType("int");

                    b.Property<double>("SoGioQuyChuan")
                        .HasColumnType("float");

                    b.HasKey("MaChiTietTaiKhaoThi");

                    b.HasIndex("MaGV");

                    b.HasIndex("MaTaiKhaoThi");

                    b.ToTable("ChiTietTaiKhaoThi", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.ChucVu", b =>
                {
                    b.Property<string>("MaChucVu")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaDinhMucMienGiam")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaChucVu");

                    b.HasIndex("MaDinhMucMienGiam");

                    b.ToTable("ChucVu", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.CongTacKhac", b =>
                {
                    b.Property<string>("MaCongTacKhac")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NamHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NoiDungCongViec")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaCongTacKhac");

                    b.ToTable("CongTacKhac", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.DinhMucGiangDay", b =>
                {
                    b.Property<string>("MaDinhMucGiangDay")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChucDanhGiangDay")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MucGiaoDuKienChatLuong_GiaoDuKienPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("dinhMucGiangDay")
                        .HasColumnType("int");

                    b.HasKey("MaDinhMucGiangDay");

                    b.ToTable("DinhMucGiangDay", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.DinhMucMienGiam", b =>
                {
                    b.Property<string>("MaDinhMucMienGiam")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DoiTuongMienGiam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GhiChuMienGiam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("TyLeMienGiam")
                        .HasColumnType("real");

                    b.HasKey("MaDinhMucMienGiam");

                    b.ToTable("DinhMucMienGiam", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.DinhMucNghienCuu", b =>
                {
                    b.Property<string>("MaDinhMucNghienCuu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChucDanhGiangDay")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DinhMucGioChuanHoatDongNghienCuuKhoaHoc")
                        .HasColumnType("int");

                    b.Property<int>("DinhMucThoiGianHoatDongNghienCuuKhoaHoc")
                        .HasColumnType("int");

                    b.HasKey("MaDinhMucNghienCuu");

                    b.ToTable("DinhMucNghienCuu", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.DoiTuongGiangDay", b =>
                {
                    b.Property<string>("MaDoiTuong")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<double>("HeSoQuyChuan")
                        .HasColumnType("float");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenDoiTuong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDoiTuong");

                    b.ToTable("DoiTuongGiangDay", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.GiaoVien", b =>
                {
                    b.Property<string>("MaGV")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaBM")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("QueQuan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SDT")
                        .HasColumnType("int");

                    b.HasKey("MaGV");

                    b.HasIndex("MaBM");

                    b.ToTable("GiaoVien", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.HocHam", b =>
                {
                    b.Property<string>("MaHocHam")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaDinhMucGiangDay")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaDinhMucNghienCuu")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenHocHam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaHocHam");

                    b.ToTable("HocHam", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.HocVi", b =>
                {
                    b.Property<string>("MaHocVi")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaGV")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenHocVi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaHocVi");

                    b.HasIndex("MaGV");

                    b.ToTable("HocVi", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.Khoa", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaChuNhiemKhoa")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoa", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.LichSuChucVu", b =>
                {
                    b.Property<string>("MaLichSuChucVu")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaChucVu")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaGV")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLichSuChucVu");

                    b.HasIndex("MaChucVu");

                    b.HasIndex("MaGV");

                    b.ToTable("LichSuChucVu", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.LichSuDangNhap", b =>
                {
                    b.Property<string>("MaLichSu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ThoiDiemDangNhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiDiemDangXuat")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLichSu");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("LichSuDangNhap", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.LichSuHocHam", b =>
                {
                    b.Property<string>("MaLSHocHam")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaGV")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaHocHam")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenHocHam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLSHocHam");

                    b.HasIndex("MaGV");

                    b.HasIndex("MaHocHam");

                    b.ToTable("LichSuHocHam", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.LoaiCongTacKhaoThi", b =>
                {
                    b.Property<string>("MaLoaiCongTacKhaoThi")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenLoaiCongTacKhaoThi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoaiCongTacKhaoThi");

                    b.ToTable("LoaiCongTacKhaoThi", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.LoaiHinhHuongDan", b =>
                {
                    b.Property<string>("MaLoaiHinhHuongDan")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenLoaiHinhHuongDan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoaiHinhHuongDan");

                    b.ToTable("LoaiHinhHuongDan", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.LoaiHoiDong", b =>
                {
                    b.Property<string>("MaLoaiHoiDong")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenLoaiHoiDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoaiHoiDong");

                    b.ToTable("LoaiHoiDong", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.LoaiNCKH", b =>
                {
                    b.Property<string>("MaLoaiNCKH")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaQuyDoi")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenLoaiNCKH")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoaiNCKH");

                    b.HasIndex("MaQuyDoi");

                    b.ToTable("LoaiNCKH", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.LyLichKhoaHoc", b =>
                {
                    b.Property<string>("MaLyLichKhoaHoc")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("HeDaoTaoDH")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaGV")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("NamCapBangSauDH")
                        .HasColumnType("int");

                    b.Property<int?>("NamCapBangTS")
                        .HasColumnType("int");

                    b.Property<int?>("NamTotNghiepDH")
                        .HasColumnType("int");

                    b.Property<string>("NganhHocDH")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayKhai")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDaoTaoDH")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NoiDaoTaoSauDH")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NoiDaoTaoTS")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("NuocDaoTaoDH")
                        .HasColumnType("int");

                    b.Property<string>("TenLuanAnSauDH")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenLuanVanTotNghiep")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ThacSiChuyenNganh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TienSiChuyenNganh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLyLichKhoaHoc");

                    b.HasIndex("MaGV");

                    b.ToTable("LyLichKhoaHoc", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.NgonNguGiangDay", b =>
                {
                    b.Property<string>("MaNgonNgu")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<double>("HeSoQuyChuan")
                        .HasColumnType("float");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenNgonNgu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNgonNgu");

                    b.ToTable("NgonNguGiangDay", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.NguoiDung", b =>
                {
                    b.Property<string>("MaNguoiDung")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaGV")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("MaGV");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.NguoiDung_Nhom", b =>
                {
                    b.Property<string>("MaNguoiDung")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(0);

                    b.Property<string>("MaNhom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(1);

                    b.HasKey("MaNguoiDung", "MaNhom");

                    b.HasIndex("MaNhom");

                    b.ToTable("NguoiDung_Nhom", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.NhatKyThayDoi", b =>
                {
                    b.Property<string>("MaNhatKy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaLichSu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NoiDungThayDoi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ThoiGianThayDoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThongTinCu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ThongTinMoi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaNhatKy");

                    b.HasIndex("MaLichSu");

                    b.ToTable("NhatKyThayDoi", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.NhomNguoiDung", b =>
                {
                    b.Property<string>("MaNhom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNhom");

                    b.ToTable("NhomNguoiDung", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.Nhom_Quyen", b =>
                {
                    b.Property<string>("MaNhom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(0);

                    b.Property<string>("MaQuyen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(1);

                    b.HasKey("MaNhom", "MaQuyen");

                    b.HasIndex("MaQuyen");

                    b.ToTable("Nhom_Quyen", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.QuanHam", b =>
                {
                    b.Property<string>("MaQuanHam")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaGV")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenQuanHam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaQuanHam");

                    b.HasIndex("MaGV");

                    b.ToTable("QuanHam", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.QuyDoiGioChuanNCKH", b =>
                {
                    b.Property<string>("MaQuyDoi")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MaNoiDung")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("NhomCongViec")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("QuyRaGioChuan")
                        .HasColumnType("float");

                    b.HasKey("MaQuyDoi");

                    b.ToTable("QuyDoiGioChuanNCKH", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.Quyen", b =>
                {
                    b.Property<string>("MaQuyen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaQuyen");

                    b.ToTable("Quyen", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.SequenceGenerator", b =>
                {
                    b.Property<string>("TableName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LastSequence")
                        .HasColumnType("int");

                    b.HasKey("TableName");

                    b.ToTable("SequenceGenerator", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.TaiGiangDay", b =>
                {
                    b.Property<string>("MaTaiGiangDay")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("He")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Lop")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaDoiTuong")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaNgonNgu")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaThoiGian")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("NamHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SiSo")
                        .HasColumnType("int");

                    b.Property<int>("SoTinChi")
                        .HasColumnType("int");

                    b.Property<string>("TenHocPhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTaiGiangDay");

                    b.HasIndex("MaDoiTuong");

                    b.HasIndex("MaNgonNgu");

                    b.HasIndex("MaThoiGian");

                    b.ToTable("TaiGiangDay", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.TaiHoiDong", b =>
                {
                    b.Property<string>("MaHoiDong")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MaLoaiHoiDong")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("NamHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.HasKey("MaHoiDong");

                    b.HasIndex("MaLoaiHoiDong");

                    b.ToTable("TaiHoiDong", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.TaiHuongDan", b =>
                {
                    b.Property<string>("MaHuongDan")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("He")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoTenHocVien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Lop")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaLoaiHinhHuongDan")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("NamHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoCBHD")
                        .HasColumnType("int");

                    b.Property<string>("TenDeTai")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaHuongDan");

                    b.HasIndex("MaLoaiHinhHuongDan");

                    b.ToTable("TaiHuongDan", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.TaiKhaoThi", b =>
                {
                    b.Property<string>("MaTaiKhaoThi")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HocPhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Lop")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaLoaiCongTacKhaoThi")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("NamHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTaiKhaoThi");

                    b.HasIndex("MaLoaiCongTacKhaoThi");

                    b.ToTable("TaiKhaoThi", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.TaiNCKH", b =>
                {
                    b.Property<string>("MaTaiNCKH")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaLoaiNCKH")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("NamHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoTacGia")
                        .HasColumnType("int");

                    b.Property<string>("TenCongTrinhKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaTaiNCKH");

                    b.HasIndex("MaLoaiNCKH");

                    b.ToTable("TaiNCKH", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.ThamGia", b =>
                {
                    b.Property<string>("MaThamGia")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaGV")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaHoiDong")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<double>("SoGio")
                        .HasColumnType("float");

                    b.HasKey("MaThamGia");

                    b.HasIndex("MaGV");

                    b.HasIndex("MaHoiDong");

                    b.ToTable("ThamGia", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.ThamGiaHuongDan", b =>
                {
                    b.Property<string>("MaThamGiaHuongDan")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaGV")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaHuongDan")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<double>("SoGio")
                        .HasColumnType("float");

                    b.HasKey("MaThamGiaHuongDan");

                    b.HasIndex("MaGV");

                    b.HasIndex("MaHuongDan");

                    b.ToTable("ThamGiaHuongDan", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.ThoiGianGiangDay", b =>
                {
                    b.Property<string>("MaThoiGian")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<double>("HeSoQuyChuan")
                        .HasColumnType("float");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenThoiGian")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaThoiGian");

                    b.ToTable("ThoiGianGiangDay", (string)null);
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.BoMon", b =>
                {
                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.ChiTietCongTacKhac", b =>
                {
                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.CongTacKhac", "CongTacKhac")
                        .WithMany()
                        .HasForeignKey("MaCongTacKhac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.GiaoVien", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("MaGV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CongTacKhac");

                    b.Navigation("GiaoVien");
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.ChiTietGiangDay", b =>
                {
                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.GiaoVien", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("MaGV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.TaiGiangDay", "TaiGiangDay")
                        .WithMany("ChiTietGiangDays")
                        .HasForeignKey("MaTaiGiangDay")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("TaiGiangDay");
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.ChiTietNCKH", b =>
                {
                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.GiaoVien", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("MaGV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.TaiNCKH", "TaiNCKH")
                        .WithMany()
                        .HasForeignKey("MaTaiNCKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("TaiNCKH");
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.ChiTietTaiKhaoThi", b =>
                {
                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.GiaoVien", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("MaGV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.TaiKhaoThi", "TaiKhaoThi")
                        .WithMany()
                        .HasForeignKey("MaTaiKhaoThi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("TaiKhaoThi");
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.ChucVu", b =>
                {
                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.DinhMucMienGiam", "DinhMucMienGiam")
                        .WithMany()
                        .HasForeignKey("MaDinhMucMienGiam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DinhMucMienGiam");
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.GiaoVien", b =>
                {
                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.BoMon", "BoMon")
                        .WithMany()
                        .HasForeignKey("MaBM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoMon");
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.HocVi", b =>
                {
                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.GiaoVien", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("MaGV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.LichSuChucVu", b =>
                {
                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.ChucVu", "ChucVu")
                        .WithMany()
                        .HasForeignKey("MaChucVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.GiaoVien", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("MaGV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVu");

                    b.Navigation("GiaoVien");
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.LichSuDangNhap", b =>
                {
                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.LichSuHocHam", b =>
                {
                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.GiaoVien", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("MaGV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.HocHam", "HocHam")
                        .WithMany()
                        .HasForeignKey("MaHocHam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("HocHam");
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.LoaiNCKH", b =>
                {
                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.QuyDoiGioChuanNCKH", "QuyDoiGioChuanNCKH")
                        .WithMany()
                        .HasForeignKey("MaQuyDoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuyDoiGioChuanNCKH");
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.LyLichKhoaHoc", b =>
                {
                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.GiaoVien", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("MaGV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.NguoiDung", b =>
                {
                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.GiaoVien", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("MaGV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.NguoiDung_Nhom", b =>
                {
                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.NhomNguoiDung", "NhomNguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNhom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("NhomNguoiDung");
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.NhatKyThayDoi", b =>
                {
                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.LichSuDangNhap", "LichSuDangNhap")
                        .WithMany()
                        .HasForeignKey("MaLichSu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LichSuDangNhap");
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.Nhom_Quyen", b =>
                {
                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.NhomNguoiDung", "NhomNguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNhom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.Quyen", "Quyen")
                        .WithMany()
                        .HasForeignKey("MaQuyen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhomNguoiDung");

                    b.Navigation("Quyen");
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.QuanHam", b =>
                {
                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.GiaoVien", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("MaGV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.TaiGiangDay", b =>
                {
                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.DoiTuongGiangDay", "DoiTuongGiangDay")
                        .WithMany()
                        .HasForeignKey("MaDoiTuong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.NgonNguGiangDay", "NgonNguGiangDay")
                        .WithMany()
                        .HasForeignKey("MaNgonNgu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.ThoiGianGiangDay", "ThoiGianGiangDay")
                        .WithMany()
                        .HasForeignKey("MaThoiGian")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoiTuongGiangDay");

                    b.Navigation("NgonNguGiangDay");

                    b.Navigation("ThoiGianGiangDay");
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.TaiHoiDong", b =>
                {
                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.LoaiHoiDong", "LoaiHoiDong")
                        .WithMany()
                        .HasForeignKey("MaLoaiHoiDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiHoiDong");
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.TaiHuongDan", b =>
                {
                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.LoaiHinhHuongDan", "LoaiHinhHuongDan")
                        .WithMany()
                        .HasForeignKey("MaLoaiHinhHuongDan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiHinhHuongDan");
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.TaiKhaoThi", b =>
                {
                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.LoaiCongTacKhaoThi", "LoaiCongTacKhaoThi")
                        .WithMany()
                        .HasForeignKey("MaLoaiCongTacKhaoThi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiCongTacKhaoThi");
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.TaiNCKH", b =>
                {
                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.LoaiNCKH", "LoaiNCKH")
                        .WithMany()
                        .HasForeignKey("MaLoaiNCKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiNCKH");
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.ThamGia", b =>
                {
                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.GiaoVien", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("MaGV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.TaiHoiDong", "TaiHoiDong")
                        .WithMany()
                        .HasForeignKey("MaHoiDong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("TaiHoiDong");
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.ThamGiaHuongDan", b =>
                {
                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.GiaoVien", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("MaGV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyGiaoVienCSDLNC.Models.TaiHuongDan", "TaiHuongDan")
                        .WithMany()
                        .HasForeignKey("MaHuongDan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("TaiHuongDan");
                });

            modelBuilder.Entity("QuanLyGiaoVienCSDLNC.Models.TaiGiangDay", b =>
                {
                    b.Navigation("ChiTietGiangDays");
                });
#pragma warning restore 612, 618
        }
    }
}
